gems:
  - jekyll-feed
highlighter: rouge
markdown: kramdown
permalink: /:title/
url: http://copslock.github.io
name: Embedded-World
author: "CopsLock"
github: copslock
safe: true
paginate: 20
about: "Blog for misc discover."
